name: Unit Tests
on:
  pull_request:
    paths:
      - '*.cs'

jobs:
  unit-tests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run unit tests
        run: |
          cd "Tests\WolvenKit.UnitTests"
          dotnet test
