name: bump-version

env:
  BRANCH: bump-version-${{ github.event.inputs.new_version }}

on:
  workflow_dispatch:
    inputs:
      new_version:
        description: "New version"
        required: true

jobs:
  bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Create new branch
        run: |
          git checkout -b ${{ env.BRANCH }}

      - name: Update WolvenKit.csproj
        run: |
          NEW_VERSION="${{ github.event.inputs.new_version }}"
          sed -i "s|<VersionPrefix>.*</VersionPrefix>|<VersionPrefix>$NEW_VERSION</VersionPrefix>|" WolvenKit/WolvenKit.csproj
          sed -i "s|<InformationalVersion>.*</InformationalVersion>|<InformationalVersion>$NEW_VERSION</InformationalVersion>|" WolvenKit/WolvenKit.csproj

      - name: Update WolvenKit.App.csproj
        run: |
          NEW_VERSION="${{ github.event.inputs.new_version }}"
          sed -i "s|<Version>.*</Version>|<Version>$NEW_VERSION</Version>|" WolvenKit.App/WolvenKit.App.csproj

      - name: Update WolvenKit.CLI.csproj
        run: |
          NEW_VERSION="${{ github.event.inputs.new_version }}"
          sed -i "s|<VersionPrefix>.*</VersionPrefix>|<VersionPrefix>$NEW_VERSION</VersionPrefix>|" WolvenKit.CLI/WolvenKit.CLI.csproj

      - name: Update WolvenKit.Common.csproj
        run: |
          NEW_VERSION="${{ github.event.inputs.new_version }}"
          sed -i "s|<Version>.*</Version>|<Version>$NEW_VERSION</Version>|" WolvenKit.Common/WolvenKit.Common.csproj

      - name: Update WolvenKit.Core.csproj
        run: |
          NEW_VERSION="${{ github.event.inputs.new_version }}"
          sed -i "s|<Version>.*</Version>|<Version>$NEW_VERSION</Version>|" WolvenKit.Core/WolvenKit.Core.csproj

      - name: Update WolvenKit.Modkit.csproj
        run: |
          NEW_VERSION="${{ github.event.inputs.new_version }}"
          sed -i "s|<VersionPrefix>.*</VersionPrefix>|<VersionPrefix>$NEW_VERSION</VersionPrefix>|" WolvenKit.Modkit/WolvenKit.Modkit.csproj

      - name: Update WolvenKit.RED4.csproj
        run: |
          NEW_VERSION="${{ github.event.inputs.new_version }}"
          sed -i "s|<Version>.*</Version>|<Version>$NEW_VERSION</Version>|" WolvenKit.RED4/WolvenKit.RED4.csproj

      - name: Update WolvenKit.Unpacker.csproj
        run: |
          NEW_VERSION="${{ github.event.inputs.new_version }}"
          sed -i "s|<Version>.*</Version>|<Version>$NEW_VERSION</Version>|" WolvenKit.Unpacker/WolvenKit.Unpacker.csproj

      - name: Update single_item_template.inkatlas.json
        run: |
          NEW_VERSION="${{ github.event.inputs.new_version }}"
          sed -i "s|\"WolvenKitVersion\": \".*\"|\"WolvenKitVersion\": \"$NEW_VERSION\"|" WolvenKit/Resources/TemplateFiles/inkatlas/single_item_template.inkatlas.json

      - name: Commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Bump version to ${{ github.event.inputs.new_version }}" || echo "No changes to commit"

      - name: Push
        run: |
          git push origin HEAD

      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            branch: ${{ env.BRANCH }}
            base: main
            title: "Bump version to ${{ github.event.inputs.new_version }}"
            body: |
              Bump the project version to `${{ github.event.inputs.new_version }} beep boop`.
