name: version-bump.yml
on:
  workflow_dispatch:
    inputs:
      target_version:
        description: "Bump Version"
        required: true
        default: "0.0.0"

jobs:
  make-branch:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create new branch
        run: |
          BRANCH="$version-bump-{{ github.event.inputs.target_version }}"

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git checkout main

          git checkout -b "$BRANCH"

          echo "hello from $BRANCH" > test.txt

          git add test.txt
          git commit -m "Create $BRANCH with changes"
          git push origin "$BRANCH"
